
package com.ccwl.webservice.control;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CcwlGpsImplService", targetNamespace = "http://control.webservice.ccwl.com/", wsdlLocation = "file:/E:/NetBeansWorkspace/CheChengGPS/src/conf/xml-resources/web-services/CcwlGpsController/wsdl/61.183.200.37_8099/ccwl/webservices/gpsservice.wsdl")
public class CcwlGpsImplService
    extends Service
{

    private final static URL CCWLGPSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CCWLGPSIMPLSERVICE_EXCEPTION;
    private final static QName CCWLGPSIMPLSERVICE_QNAME = new QName("http://control.webservice.ccwl.com/", "CcwlGpsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/NetBeansWorkspace/CheChengGPS/src/conf/xml-resources/web-services/CcwlGpsController/wsdl/61.183.200.37_8099/ccwl/webservices/gpsservice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CCWLGPSIMPLSERVICE_WSDL_LOCATION = url;
        CCWLGPSIMPLSERVICE_EXCEPTION = e;
    }

    public CcwlGpsImplService() {
        super(__getWsdlLocation(), CCWLGPSIMPLSERVICE_QNAME);
    }

    public CcwlGpsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CCWLGPSIMPLSERVICE_QNAME, features);
    }

    public CcwlGpsImplService(URL wsdlLocation) {
        super(wsdlLocation, CCWLGPSIMPLSERVICE_QNAME);
    }

    public CcwlGpsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CCWLGPSIMPLSERVICE_QNAME, features);
    }

    public CcwlGpsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CcwlGpsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CcwlGps
     */
    @WebEndpoint(name = "CcwlGpsImplPort")
    public CcwlGps getCcwlGpsImplPort() {
        return super.getPort(new QName("http://control.webservice.ccwl.com/", "CcwlGpsImplPort"), CcwlGps.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CcwlGps
     */
    @WebEndpoint(name = "CcwlGpsImplPort")
    public CcwlGps getCcwlGpsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://control.webservice.ccwl.com/", "CcwlGpsImplPort"), CcwlGps.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CCWLGPSIMPLSERVICE_EXCEPTION!= null) {
            throw CCWLGPSIMPLSERVICE_EXCEPTION;
        }
        return CCWLGPSIMPLSERVICE_WSDL_LOCATION;
    }

}
