
package com.ccwl.webservice.control;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CcwlGps", targetNamespace = "http://webservice.ccwl.com/")
@XmlSeeAlso({
    com.ccwl.webservice.ObjectFactory.class,
    com.ccwl.webservice.control.ObjectFactory.class
})
public interface CcwlGps {


    /**
     * 
     * @param address
     * @param carno
     * @param latitude
     * @param supplierno
     * @param stime
     * @param gpsno
     * @param pwd
     * @param speed
     * @param longitude
     * @param direction
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addGpsImpl", targetNamespace = "http://webservice.ccwl.com/", className = "com.ccwl.webservice.AddGpsImpl")
    @ResponseWrapper(localName = "addGpsImplResponse", targetNamespace = "http://webservice.ccwl.com/", className = "com.ccwl.webservice.AddGpsImplResponse")
    public String addGpsImpl(
        @WebParam(name = "supplierno", targetNamespace = "http://control.webservice.ccwl.com/")
        String supplierno,
        @WebParam(name = "pwd", targetNamespace = "http://control.webservice.ccwl.com/")
        String pwd,
        @WebParam(name = "carno", targetNamespace = "http://control.webservice.ccwl.com/")
        String carno,
        @WebParam(name = "gpsno", targetNamespace = "http://control.webservice.ccwl.com/")
        String gpsno,
        @WebParam(name = "longitude", targetNamespace = "http://control.webservice.ccwl.com/")
        String longitude,
        @WebParam(name = "latitude", targetNamespace = "http://control.webservice.ccwl.com/")
        String latitude,
        @WebParam(name = "stime", targetNamespace = "http://control.webservice.ccwl.com/")
        String stime,
        @WebParam(name = "address", targetNamespace = "http://control.webservice.ccwl.com/")
        String address,
        @WebParam(name = "speed", targetNamespace = "http://control.webservice.ccwl.com/")
        String speed,
        @WebParam(name = "direction", targetNamespace = "http://control.webservice.ccwl.com/")
        String direction);

    /**
     * 
     * @param gpslist
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addGpssImpl", targetNamespace = "http://webservice.ccwl.com/", className = "com.ccwl.webservice.AddGpssImpl")
    @ResponseWrapper(localName = "addGpssImplResponse", targetNamespace = "http://webservice.ccwl.com/", className = "com.ccwl.webservice.AddGpssImplResponse")
    public String addGpssImpl(
        @WebParam(name = "gpslist", targetNamespace = "http://control.webservice.ccwl.com/")
        String gpslist);

}
