<?xml version="1.0" ?><wsdl:definitions name="CcwlGpsImplService" targetNamespace="http://control.webservice.ccwl.com/" xmlns:ns1="http://webservice.ccwl.com/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://control.webservice.ccwl.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="http://10.2.9.17/ccwl/webservices/gpsservice?wsdl=CcwlGps.wsdl" namespace="http://webservice.ccwl.com/">
    </wsdl:import>
  <wsdl:binding name="CcwlGpsImplServiceSoapBinding" type="ns1:CcwlGps">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"></soap:binding>
    <wsdl:operation name="addGpsImpl">
      <soap:operation soapAction="" style="document"></soap:operation>
      <wsdl:input name="addGpsImpl">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="addGpsImplResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="addGpssImpl">
      <soap:operation soapAction="" style="document"></soap:operation>
      <wsdl:input name="addGpssImpl">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="addGpssImplResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CcwlGpsImplService">
    <wsdl:port binding="tns:CcwlGpsImplServiceSoapBinding" name="CcwlGpsImplPort">
      <soap:address location="http://10.2.9.17/ccwl/webservices/gpsservice"></soap:address>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>